# Generated by Django 5.0.3 on 2024-03-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='phot',
            new_name='photo',
        ),
    ]
