# Generated by Django 5.0.3 on 2024-04-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_Accepted',
            new_name='is_accepted',
        ),
    ]
